name: FleshBall
version: 1.0
main: com.graveyard.fleshball.FleshBallPlugin
api-version: 1.21

commands:
  fleshball:
    description: FleshBall swarm master management framework command.
    usage: /fleshball help
    permission: fleshball.admin
    permission-message: §cYou do not have permission to execute this command!